### ISSUE TITLE
Release planning

### ISSUE THREAD

**Issue by adinapoli** [ucsd-progsys/liquidhaskell#1694]
Now that we merged our work on the [GHC Plugin](https://github.com/ucsd-progsys/liquidhaskell/pull/1683), it's time for us to think about a new LH release. In particular, there are a number of things we need to do/think about before we are ready to cut a new release. In no particular order:

- [x] **Script** the lock-step upload of LH and all associated packages on hackage.

- [x] **Speedup LH development with plugin** Make sure development of LH does not have to not rebuild all 200+ `liquid-base` modules etc.

- [x] **Merge any outstanding PRs**. I would like to get in #1690 and #1691. The former is innocuous but simplifies the stack/cabal manifests users have to write, the latter greatly simplify the plugin architecture while allowing basic integration into IDEs and tools like `ghcid`; 

- [x] **Organise the available documentation and tutorials**. I have tried my best to write some documentation for the plugin (as well as amending the current `README`) but we should make sure this is polished enough to be consumed by users in a meaningful way. To name one glaring omission, we should do a better job in describing that users have to add things like `liquid-base` in their cabal manifests. (See #1689 on why it's important). See this [helpful issue](https://github.com/ucsd-progsys/liquidhaskell/issues/1694#issuecomment-657013481)

- [x] **Make a final call on the new naming scheme**. Should we stick with the current plan of having a `liquid-legacy` and the new executable as part of the `liquid-platform` or should we minimise breakage by having the "legacy" executable named `liquid` as-it-is-now, ship it as part of the `liquidhaskell` package and have the `liquid-platform` named differently and ship the new executable with it? Both approaches have pros & cons to evaluate, both in terms of breakage and traction/adoption of the plugin.

- [x] **Decide where to host the `liquid-*` packages**. They are currently hosted as part of this repo (which essentially becomes a "megarepo") but we could also think about moving them outside this package, so that contributing changes to them individually it's potentially easier.

- [x] **Decide the final version for the LH "core" packages**. Are we happy to keep tracking the GHC version or should we also bump the major digit to signify this is a breaking change? In practical terms, should we go with `0.8.10.1` or `1.8.10.1`?

- [x] **Decide on a versioning scheme for the LH ecosystem**. (cfr #1696) From a conversation I had with @kosmikus it's fairly clear that our preference would be to **not** track the GHC version as part of the scheme, but rather trying to track _at least_ the upstream version (for obvious reasons), making the transition from/to LH as light as possible. As a practical example, given something like `base-4.14`, we would simply release `liquid-base-4.14`, and **only** in case of bug fixes _of our own wrapper packages_ (e.g. a bug in one spec) we would release a new version embellished with the "revision" number, which could track both changes to the LH language and/or changes to the package itself. For example, we could have something like `liquid-base-4.14.0.1` if we release a new version by fixing a bug or `liquid-base-4.14.1.0` if we have to rely on a specific feature of LH for the library to work correctly. There are more complicated versioning scheme we have discussed (which I can share here as well), but it has to be seen that the extra complexity they add is justified in terms of what those buy us.

**Comment by kosmikus** [comment]
#### Make a final call on the new naming scheme

I'm now in favour of reverting this and leaving the old executable under the name `liquid`, and calling the new one, perhaps, `lh` (which seems to be not taken by anything really important). I'm also in favour of moving the legacy binary back into the main `liquidhaskell` package. I find the flag logic very strange, where in `liquid-platform` we currently can only build one of the binaries.

#### Decide where to host the `liquid-*` packages

I'm in favour of keeping them in the repo, but then again, I'm generally becoming more fond of megarepos. I find it mildly annoying already that `liquid-fixpoint` is its own package. Do we benefit from having separate issue trackers on these? I don't think so, for now. It's more likely there are issues affecting multiple of these packages plus LH itself.

**Comment by gridaphobe** [comment]
> Decide where to host the liquid-* packages
> I'm in favour of keeping them in the repo, but then again, I'm generally becoming more fond of megarepos. I find it mildly annoying already that liquid-fixpoint is its own package. Do we benefit from having separate issue trackers on these? I don't think so, for now. It's more likely there are issues affecting multiple of these packages plus LH itself.

My thinking is that megarepos are useful when the underlying components are tightly coupled and have to co-evolve. In other words, if you find yourself submitting a lot of coordinated PRs between two packages, or coordinating their release schedules, you might benefit from a megarepo.

When we split liquid-fixpoint out into its own repo, I think we imagined it being a relatively stable base that could evolve separately from LH. (There were also a few other active research projects that used liquid-fixpoint as their own backend, I don't know if that's still the case.) I haven't been involved in LH in a while, but in my experience liquid-fixpoint and LH were much more tightly coupled than we had anticipated.

So I agree that merging the two repos again would make sense.

**Comment by kosmikus** [comment]
I agree with the general assessment by @gridaphobe. I did not want to start entangling the next release with the question of possibly merging `liquid-fixpoint` back into the main repo. I would be in favour of this, but even if, let's not do it before the next release. However, I think for the new library packages, we should keep them in the main repo for now, at least until we feel that they're stabilising and perhaps evolving on their own.

**Comment by ranjitjhala** [comment]
Hi all, yes liquid-fixpoint is in fact still used by projects unrelated to
LH
so we'll have to keep that separate. The rest I don't really have a super
strong
opinion on... Ranjit.

**Comment by nikivazou** [comment]
**Decide where to host the 'liquid-*' packages**

The benefit of holding them outside of the LH repo is that a contributor can more easily modify, provide other `liquid-*` packages. E.g., is the base package in the same repo as ghc? 

**Make a final call on the new naming scheme**
I also dislike `liquid-legacy`. How about `liquidhaskell` for the new name?

**Comment by kosmikus** [comment]
@nikivazou `base` (and `ghc-prim`) are in the main repo. The other libraries are submodules. I don't think having separate repos makes these libraries easier to "modify". In order to provide new libraries, everyone can make their own `liquid` wrapper in their own repository. We're not preventing that. But these would not be maintained by the LH team.

**Comment by ranjitjhala** [comment]
If anything I'd say `liquid-base` and `liquid-prim` are easier
to modify when they are _inside_, because you can easily rebuild
LH with them to make sure you didn't make some odd typo/mistake.

**Comment by safinaskar** [comment]
Hi. I am trying to get started with Liquid Haskell. I want to report some issues (mostly with docs) I found. I hope I helped you.

Currently I see documentation mess:
- http://ucsd-progsys.github.io/lh-workshop/ has this link labeled as "PDF": http://ucsd-progsys.github.io/lh-workshop/book.pdf , but this link is broken
- https://ucsd-progsys.github.io/lh-workshop/01-index.html has link http://www.refinement-types.org/ and it is broken
- http://ucsd-progsys.github.io/liquidhaskell-tutorial/ has link "PDF". But http://ucsd-progsys.github.io/liquidhaskell-tutorial/ contains 12 sections, but PDF - 11
- There are multiple "main sites" of Liquid Haskell with slightly different look and duplicate info
  - http://ucsd-progsys.github.io/liquidhaskell/ - site with blue panel at the top with labels "Home, Install, Run, Options, Specification, Community, etc"
  - https://ucsd-progsys.github.io/liquidhaskell-blog/ - another "main site" of Liquid Haskell with gray panel at the top with labels "Blog, Demo, Tutorial, etc"
- https://ucsd-progsys.github.io/liquidhaskell-blog/ shows cool animations, but doesn't say what IDE I should install to actually see this locally. I found that Emacs and vim plugins are available. But how you created that animations? Using Emacs or Vim? I should try both to know this?!!!
- https://github.com/ucsd-progsys/liquidhaskell/blob/develop/docs/mkDocs/docs/install.md suggests running "cabal install liquid-platform", but there is no such package

More mess:
- http://goto.ucsd.edu:8090/index.html#?demo=SimpleRefinements.hs checks the example as unsafe

Also, I was unable to find list of all commands Liquid Haskell supports (with short explanations). I mean "assume", "reflect", "assert" etc. For example, I still unable to find what "assume" and "assert" mean. I looked in http://ucsd-progsys.github.io/liquidhaskell/specifications/ and http://ucsd-progsys.github.io/liquidhaskell-tutorial/book.pdf

**Comment by ranjitjhala** [comment]
Wow this is *very* helpful and comprehensive thank you very much! (We're working to "collect" all these dead links and exactly fix up this kind of stuff, so its perfect to have a fresh set of eyes tell us what needs fixing)

**Comment by adinapoli** [comment]
The `0.8.10.1` release is now on Hackage, together with the ancillary packages:

* https://hackage.haskell.org/package/liquidhaskell-0.8.10.1
* https://hackage.haskell.org/package/liquid-fixpoint-0.8.10.1
* https://hackage.haskell.org/package/liquid-base-4.14.0.0
* https://hackage.haskell.org/package/liquid-ghc-prim-0.6.1
* https://hackage.haskell.org/package/liquid-bytestring-0.10.10.0
* https://hackage.haskell.org/package/liquid-containers-0.6.2.1
* https://hackage.haskell.org/package/liquid-parallel-3.2.2.0
* https://hackage.haskell.org/package/liquid-platform-0.8.10.1
* https://hackage.haskell.org/package/liquid-prelude-0.8.10.1
* https://hackage.haskell.org/package/liquid-vector-0.12.1.2
* https://hackage.haskell.org/package/liquid-ghc-prim-0.6.1
